import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { catchError } from 'rxjs/operators';


@Injectable({
    providedIn: 'root'
})
export class City_list{
    constructor() { 

    }

   sheet1 = [{"id":1,"name":"American"},{"id":2,"name":"Asian"},{"id":3,"name":"Brazilian"},{"id":4,"name":"Burgers"},{"id":5,"name":"Cakes & Bakery"},{"id":6,"name":"Chicken"},{"id":7,"name":"Chinese"},{"id":8,"name":"Desserts"},{"id":9,"name":"Fast food"},{"id":10,"name":"Filipino"},{"id":11,"name":"French"},{"id":12,"name":"German"},{"id":13,"name":"Greek"},{"id":14,"name":"Halal"},{"id":15,"name":"Healthy food"},{"id":16,"name":"Indian"},{"id":17,"name":"International"},{"id":18,"name":"Italian"},{"id":19,"name":"Japanese"},{"id":20,"name":"Korean"},{"id":21,"name":"Mediterranean"},{"id":22,"name":"Mexican"},{"id":23,"name":"Middle Eastern"},{"id":24,"name":"Non-alcoholic Drinks"},{"id":25,"name":"Pizza"},{"id":26,"name":"Sandwiches"},{"id":27,"name":"Sea Food"},{"id":28,"name":"Singaporean"},{"id":29,"name":"South East Asian"},{"id":30,"name":"Spanish"},{"id":31,"name":"Sushi"},{"id":32,"name":"Thai"},{"id":33,"name":"Vegetarian"},{"id":34,"name":"Vietnamese"},{"id":35,"name":"Western"},{"id":36,"name":" Swedish"},{"id":37,"name":" Latvian"},{"id":38,"name":"Scottish"},{"id":39,"name":" British"},{"id":40,"name":"Canadian"},{"id":41,"name":"Russian"},{"id":42,"name":"Jewish"},{"id":43,"name":"Polish"},{"id":44,"name":" Hawaiian"},{"id":45,"name":" Peruvian"},{"id":46,"name":"Salvadorian"},{"id":47,"name":"Cuban"},{"id":48,"name":"Tibetan"},{"id":49,"name":"Egyptian"},{"id":50,"name":" Belgian"},{"id":51,"name":"Irish"},{"id":52,"name":"Welsh"},{"id":53,"name":"Mormon"},{"id":54,"name":"Cajun"},{"id":55,"name":"Portuguese"},{"id":56,"name":"Turkish"},{"id":57,"name":" Haitian"},{"id":58,"name":"Tahitian"},{"id":59,"name":"Kenyan"},{"id":60,"name":"Algerian"},{"id":61,"name":"Nigerian"},{"id":62,"name":" Libyan"},{"id":63,"name":"Malaysian"}];
   sheet2 = [{"id":1,"name":"Animals & Pet Supplies"},
   {"id":2,"name":"Apparel & Accessories"},
   {"id":3,"name":"Animals & Pet Supplies > Pet Supplies"},
   {"id":4,"name":"Arts & Entertainment"},
   {"id":5,"name":"Business & Industrial"},
   {"id":6,"name":"Cameras & Optics"},
   {"id":7,"name":"Electronics"},
   {"id":8,"name":"Food, Beverages & Tobacco"},
   {"id":9,"name":"Furniture"},
   {"id":10,"name":"Hardware"},
   {"id":11,"name":"Health & Beauty"},
   {"id":12,"name":"Home & Garden"},
   {"id":13,"name":"Luggage & Bags"},
   {"id":14,"name":"Mature"},
   {"id":15,"name":"Media"},
   {"id":16,"name":"Office Supplies"},
   {"id":17,"name":"Religious & Ceremonial"},
   {"id":18,"name":"Software"},
   {"id":19,"name":"Sporting Goods"},
   {"id":20,"name":"Toys & Games"},
   {"id":21,"name":"Vehicles & Parts"}];


   lang_eng = {
    "choose_cat":"Choose Category",
    "product_name":"Product Name",
    "product_img" : "Product image",
    "preorder":"Pre Order",
    "item_name" : "Item Name (Max 80 Character)",
    "item_code":"Item Code(Auto Generate)",
    "choose_menu_available_time":"Choose Menu Availabilty Time",
    "from_time":"From Time",
    "to_time":"To Time",
    "product_pricing" : "Product Pricing",
    "description":"Description",
    "description_title":"Description Title",
    "product_description":"Product Description (max- 2000 Characters)",
    "add_button":"Add",
    "save_button":"Save",
    "cancel_button":"Cancel",
    "select_cat":"Select Category",
    "enter_category_name":"Enter Category Name",
    "add_category":"Add Category",
    "save_changes":"Save changes",
    "product_list":"Product List",
    "select_language":"Select Language",
    "s_no":"S.no",
    "more":"more",
    "category_id":"category id",
    "category_name":"Category name",
    "total_items":"Total items",
    "add_product":"Add Product",
    "view_product":"View Product",
    "revome_category":"Revome Category",
    "edit_category":"Edit Category",
    "edit_product":"Edit Product",
    "yummy_rate":"yummy_rate",
    "close_button":"Close",
    "remove_product":"",
   };


   lang_tam = {
    "choose_cat":"வகையைத் தேர்ந்தெடுக்கவும்",
    "product_name":"பொருளின் பெயர்",
    "product_img" : "பொருளின படம்",
    "preorder":"முன்பதிவு",
    "item_name" : "பொருளின் பெயர் (அதிகபட்சம் 80 எழுத்துகள்)",
    "item_code":"பொருள் குறியீடு(தானாக உருவாக்குதல்)",
    "choose_menu_available_time":"மெனு கிடைக்கும் நேரத்தைத் தேர்ந்தெடுக்கவும்",
    "from_time":"இந்த நேரத்தில் இருந்து",
    "to_time":"இந்த நேரம் வரை",
    "product_pricing" : "தயாரிப்பு விலை",
    "description":"விளக்கம்",
    "description_title":"விளக்கம் தலைப்பு",
    "product_description":"தயாரிப்பு விளக்கம் (அதிகபட்சம்- 2000 எழுத்துகள்)",
    "add_button":"சேர்க்க",
    "save_button":"சேமிக்கவும்",
    "cancel_button":"ரத்து செய்",
    "select_cat":"பிரிவை தேர்வு செய்க",
    "enter_category_name":"வகை பெயரை உள்ளிடவும்",
    "add_category":"வகையைச் சேர்க்கவும்",
    "save_changes":"மாற்றத்தை சேமிக்கவும்",
    "product_list":"தயாரிப்பு பட்டியல்",
    "select_language":"மொழியை தேர்ந்தெடுங்கள்",
    "s_no":"வ.எண்",
    "more":"மேலும்",
    "category_id":"வகை ஐடி",
    "category_name":"வகை பெயர்",
    "total_items":"மொத்த பொருட்கள்",
    "add_product":"இந்த தயாரிப்பைச் சேர்க்கவும்",
    "view_product":"இந்த தயாரிப்பைப் பார்க்க",
    "revome_category":"வகையை அகற்று",
    "edit_category":"வகையைத் திருத்தவும்",
    "edit_product":"தயாரிப்பைத் திருத்து",
    "yummy_rate":"யாமிஸ் மதிப்பீடு",
    "close_button":"மூடுக",
    "remove_product":"இந்த தயாரிப்பை அகற்று",
   };


   lang_hin = {
    "choose_cat":"श्रेणी का चयन करें",
    "product_name":"प्रोडक्ट का नाम",
    "product_img" : "उत्पाद का चित्र",
    "preorder":"पूर्व आदेश",
    "item_name" : "आइटम का नाम (अधिकतम 80 वर्ण)",
    "item_code":"आइटम कोड (ऑटो जेनरेट)",
    "choose_menu_available_time":"मेनू उपलब्धता समय चुनें",
    "from_time":"इस समय से",
    "to_time":"इस समय तक",
    "product_pricing" : "उत्पाद मूल्य निर्धारण",
    "description":"विवरण",
    "description_title":"विवरण शीर्षक",
    "product_description":"उत्पाद विवरण (अधिकतम- 2000 वर्ण)",
    "add_button":"जोड़ें",
    "save_button":"सहेजें",
    "cancel_button":"रद्द करें",
    "select_cat":"श्रेणी चुनना",
    "enter_category_name":"श्रेणी का नाम दर्ज करें",
    "add_category":"कैटेगरी जोड़े",
    "save_changes":"परिवर्तनों को सुरक्षित करें",
    "product_list":"उत्पादों की सूची",
    "select_language":"भाषा चुने",
    "s_no":"क्रमिक संख्या",
    "more":"अधिक",
    "category_id":"श्रेणी ID",
    "category_name":"श्रेणी नाम",
    "total_items":"कुल सामान",
    "add_product":"उत्पाद जोड़ें",
    "view_product":"उत्पाद देखें",
    "revome_category":"श्रेणी हटाएं",
    "edit_category":"श्रेणी संपादित करें",
    "edit_product":"उत्पाद संपादित करें",
    "yummy_rate":"यामी रेटिंग्स",
    "close_button":"बंद करे",
    "remove_product":"उत्पाद निकालें",
   };


   lang_mal = {
    "choose_cat": "Pilih Kategori",
    "product_name":"Nama Produk",
    "product_img" : "Imej produk",
    "preorder":"Pra Tempahan",
    "item_name" : "Nama Item (Maks 80 Aksara)",
    "item_code":"Kod Item(Jana Auto)",
    "choose_menu_available_time":"Pilih Menu Masa Ketersediaan",
    "from_time":"Dari masa",
    "to_time":"Kepada Masa",
    "product_pricing" : "Harga Produk",
    "description":"Penerangan",
    "description_title":"Tajuk Penerangan",
    "product_description":"Penerangan Produk (maks- 2000 Aksara)",
    "add_button":"Tambah",
    "save_button":"Jimat",
    "cancel_button":"Batal",
    "select_cat":"Pilih Kategori",
    "enter_category_name":"Masukkan Nama Kategori",
    "add_category":"Tambah Kategori",
    "save_changes":"Simpan perubahan",
    "product_list":"Senarai produk",
    "select_language":"Pilih Bahasa",
    "s_no":"S.no",
    "more":"lebih",
    "category_id":"id kategori",
    "category_name":"Nama kategori",
    "total_items":"Jumlah item",
    "add_product":"Tambah Produk",
    "view_product":"Lihat Produk",
    "revome_category":"Alih Keluar Kategori",
    "edit_category":"Edit Kategori",
    "edit_product":"Edit Produk",
    "yummy_rate":"kadar sedap",
    "close_button":"tutup",
    "remove_product":"keluarkan Produk",
   };


   lang_chin = {
    "choose_cat":  "选择类别",
    "product_name":  "产品名称",
    "product_img" :  "产品图片",
    "preorder":  "预购",
    "item_name" : "项目名称（最多 80 个字符）",
    "item_code":  "项目代码（自动生成）",
    "choose_menu_available_time":  "选择菜单可用时间",
    "from_time":  "从时间",
    "to_time":  "时间",
    "product_pricing" :  "产品定价",
    "description":  "描述",
    "description_title":  "描述 标题",
    "product_description":  "产品描述（最多 2000 个字符）",
    "add_button":  "添加",
    "save_button":  "保存",
    "cancel_button":  "取消",
    "select_cat":  "选择类别",
    "enter_category_name":  "输入类别名称",
    "add_category":  "添加类别",
    "save_changes":  "保存更改",
    "product_list":  "产品列表",
    "select_language":  "选择语言",
    "s_no":  "编号",
    "more":  "更多的",
    "category_id":  "类别编号",
    "category_name":  "分类名称",
    "total_items":  "总项目",
    "add_product":  "添加产品",
    "view_product":  "查看产品",
    "revome_category":  "删除类别",
    "edit_category":  "编辑类别",
    "edit_product":  "编辑产品",
    "yummy_rate":  "好吃的评价",
    "close_button":  "关闭",
    "remove_product":"移除产品",
   };


   lang_sinhala = {
    "choose_cat":  "වර්ගය තෝරන්න",
    "product_name":  "නිෂ්පාදන නාමය",
    "product_img" :  "නිෂ්පාදන රූපය",
    "preorder":  "පූර්ව ඇණවුම",
    "item_name" : "අයිතමයේ නම (උපරිම අක්ෂර 80)",
    "item_code":  "අයිතම කේතය (ස්වයං ජනනය)",
    "choose_menu_available_time":  "මෙනු ලබා ගත හැකි කාලය තෝරන්න",
    "from_time":  "කාලයෙන්",
    "to_time":  "කාලයට",
    "product_pricing" :  "නිෂ්පාදන මිලකරණය",
    "description":  "විස්තර",
    "description_title":  "විස්තර මාතෘකාව",
    "product_description":  "නිෂ්පාදන විස්තරය (උපරිම - අක්ෂර 2000)",
    "add_button":  "එකතු කරන්න",
    "save_button":  "සුරකින්න",
    "cancel_button":  "අවලංගු කරන්න",
    "select_cat":  "වර්ගය තෝරන්න",
    "enter_category_name":  "ප්",
    "add_category":  "ප්",
    "save_changes":  "වෙනස්කම් සුරකින්න",
    "product_list":  "නිෂ්පාදන ලැයිස්තුව",
    "select_language":  "භාෂාව තෝරන්න",
    "s_no":  "අන්රක්රමික අංකය",
    "more":  "තව",
    "category_id":  "ප්රවර්ග id",
    "category_name":  "කාණ්ඩයේ නම",
    "total_items":  "මුළු අයිතම",
    "add_product":  "නිෂ්පාදන එකතු කරන්න",
    "view_product":  "නිෂ්පාදනය බලන්න",
    "revome_category":  "ප්",
    "edit_category":  "ප්",
    "edit_product":  "නිෂ්පාදනය සංස්කරණය කරන්න",
    "yummy_rate":  "රසවත් ශ්",
    "close_button":  "වසන්න",
    "remove_product":"නිෂ්පාදන ඉවත් කරන්න",
   };
}